// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"
	"flag"

	"github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	"github.com/negiseijin/clean-architectur-swagger/gen/restapi"
	"github.com/negiseijin/clean-architectur-swagger/gen/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

var portFlag = flag.Int("port", 3000, "Port to run this service on")

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewCleanArchitectureServerAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Clean Architectur Server"
	parser.LongDescription = "clean-architectur-swagger"
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	flag.Parse()
	server.Port = *portFlag

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
