swagger: "2.0"
info:
  version: 1.0.0
  title: Clean Architecture Server
  description: clean-architecture-swagger
consumes:
  - application/json
produces:
  - application/json
schemes:
  - "http"
host: localhost:3000
basePath: /
tags:
  - name: "todo"
    description: todo
paths:
  /get-todo:
    $ref: ./sub_system/business/screen/get_todo_list.yml
  /get-todo/{todoId}:
    $ref: ./sub_system/business/screen/get_todo.yml
  /create-todo:
    $ref: ./sub_system/business/screen/create_todo.yml
  /update-todo:
    $ref: ./sub_system/business/screen/update_todo_list.yml
  /update-todo/{todoId}:
    $ref: ./sub_system/business/screen/update_todo.yml
