consumes:
- application/json
produces:
- application/json
schemes:
- http
swagger: "2.0"
info:
  description: clean-architecture-swagger
  title: Clean Architecture Server
  version: 1.0.0
host: localhost:3000
basePath: /
paths:
  /get-hello:
    get:
      tags:
      - hello
      summary: こんにちは取得
      operationId: getGreeting
      responses:
        "200":
          description: returns a greeting
          schema:
            $ref: '#/definitions/helloList'
definitions:
  hello:
    type: object
    properties:
      date:
        type: string
        format: date
        example: "2022-02-24"
      greet:
        type: string
        example: こんにちは
      id:
        type: integer
        format: int32
  helloList:
    type: array
    items:
      $ref: '#/definitions/hello'
tags:
- description: こんにちは
  name: hello
